name: kir
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.4
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  get: ^4.6.6
  flutter_svg: ^2.0.16

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter


  
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/on_boarding/
    - assets/images/